---
sudo: falseo
language: go
go:
  - 1.10.x
git:
  depth: 1
install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
script:
  - make test
  - ${GOPATH}/bin/goveralls -service=travis-ci
